# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-05-02 14:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 5, 2, 14, 3, 26, 745906, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
