# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-05-04 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_tag_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
