# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-05-04 09:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_tag_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2018, 5, 4, 9, 35, 7, 165410, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
