# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-05-06 08:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_tag_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='url',
        ),
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(default=datetime.datetime(2018, 5, 6, 8, 30, 46, 726120, tzinfo=utc), upload_to='Stinagram/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
