# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-05-06 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0009_auto_20180506_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='title',
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Location'),
        ),
    ]
