# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-05-06 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0011_auto_20180506_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='location',
        ),
    ]
