# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-05-06 09:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0012_remove_photo_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='tag',
        ),
        migrations.AddField(
            model_name='photo',
            name='tag',
            field=models.ForeignKey(to='rango.Tag', 
            on_delete=django.db.models.deletion.CASCADE),
            preserve_default=False,
        ),
    ]
