# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0013_auto_20180506_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='Location',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
