# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-05-23 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0015_auto_20180523_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='views',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='views',
        ),
    ]
